"""
Publish flow: create a markdown file with frontmatter, commit it to a new branch,
open a PR. The PR-merge IS the approval action.
"""

import os
import json
import re
from datetime import datetime
from pathlib import Path
from github import BadCredentialsException, Github
from dotenv import load_dotenv

load_dotenv()

_repo = None


def _get_repo():
    """Connect to GitHub only when publishing (not at import time)."""
    global _repo
    if _repo is not None:
        return _repo
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    full_name = os.environ.get("GITHUB_REPO", "").strip()
    if not token or not full_name:
        raise RuntimeError(
            "Set GITHUB_TOKEN and GITHUB_REPO in .env (e.g. GITHUB_REPO=owner/repo)."
        )
    try:
        gh = Github(token)
        _repo = gh.get_repo(full_name)
        return _repo
    except BadCredentialsException as e:
        raise RuntimeError(
            "GitHub returned 401 Bad credentials. Fix GITHUB_TOKEN in .env: "
            "use a valid PAT with repo access, no stray quotes/spaces, and not an expired token."
        ) from e


def build_frontmatter(metadata: dict, source_url: str) -> str:
    """Build YAML frontmatter for the Astro blog post."""
    tags_yaml = "\n  - ".join([""] + metadata.get("tags", []))
    faq_yaml_blocks = []
    for entry in metadata.get("faq_schema", []):
        q = entry["question"].replace('"', '\\"')
        a = entry["answer"].replace('"', '\\"')
        faq_yaml_blocks.append(f'  - question: "{q}"\n    answer: "{a}"')
    faq_yaml = "\n".join(faq_yaml_blocks)

    return f"""---
title: "{metadata['title']}"
slug: "{metadata['slug']}"
description: "{metadata['meta_description']}"
author: "Terret Editorial"
date: "{datetime.now().strftime('%Y-%m-%d')}"
source_post: "{source_url}"
primary_keyword: "{metadata['primary_keyword']}"
tags:{tags_yaml}
read_time: {metadata.get('estimated_read_time_minutes', 4)}
faq:
{faq_yaml}
---

"""


def slugify(s: str) -> str:
    s = re.sub(r'[^a-zA-Z0-9]+', '-', s.lower())
    return s.strip('-')


def publish_draft_as_pr(result: dict) -> str:
    repo = _get_repo()
    metadata = result["metadata"]
    draft = result["draft_final"]
    source_url = result["source_post"]["url"]
    slug = metadata["slug"]

    file_path = f"site/src/content/posts/{slug}.md"
    full_content = build_frontmatter(metadata, source_url) + draft

    # Create a new branch from main
    main = repo.get_branch("main")
    branch_name = f"draft/{slug}"
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main.commit.sha)
    except Exception:
        # Branch already exists
        pass

    # Commit the file on the new branch
    try:
        repo.create_file(
            path=file_path,
            message=f"Add draft: {metadata['title']}",
            content=full_content,
            branch=branch_name
        )
    except Exception as e:
        print(f"Warning: file may already exist on branch — {e}")
        # Try to update instead
        existing = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            path=file_path,
            message=f"Update draft: {metadata['title']}",
            content=full_content,
            sha=existing.sha,
            branch=branch_name
        )

    # Open a PR
    pr_body = f"""## Auto-generated draft for review

**Source:** {source_url}

**Approval mechanism:** merging this PR publishes the post via the auto-deploy pipeline.

### Eval results
- **Genericness:** {result['evals']['genericness']['score']}/10 ({'Terret-specific ✅' if not result['evals']['genericness']['is_generic'] else 'Generic ❌'})
- **Voice fit:** {result['evals']['voice_fit']['voice_fit_score']}/10
- **AEO compliance:** {'✅' if result['evals']['aeo_compliance']['passes'] else '❌ ' + str(result['evals']['aeo_compliance']['issues'])}

### Reviewer actions
- ✅ **Approve & publish:** merge this PR
- ❌ **Reject:** close this PR without merging
- ✏️ **Request edits:** leave a review comment

---
*Generated by the Terret content workflow.*
"""

    pr = repo.create_pull(
        title=f"📝 {metadata['title']}",
        body=pr_body,
        head=branch_name,
        base="main"
    )
    return pr.html_url